# This is a basic workflow that is manually triggered

name: Release workflow

on:  
  push:
    tags:
      - v*
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Environment'
        # Default value if no value is explicitly provided
        default: 'Develop'
        # Input has to be provided for the workflow to run
        required: true

# Creates a release whenever a new change gets pushed onto the dev branch
# https://github.com/ncipollo/release-action
jobs:
  build:
    name: setup environment 
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
            
      - name: Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1.4.4
        with:
          node-version: ${{ matrix.node-version }}
        
      - name: npm install      
        run: |
          npm i
          npm run build:ci  
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.TOKEN }}
